# Generated by Django 3.0.7 on 2020-06-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200610_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
