# Generated by Django 3.0.7 on 2020-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200624_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.TextField(default='blank', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(default='blank', max_length=300),
        ),
    ]
